// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkillUp.Infrastructure.Database.Context;

#nullable disable

namespace SkillUp.Infrastructure.Migrations
{
    [DbContext(typeof(SkillUpDbContext))]
    partial class SkillUpDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SkillUp.Domaine.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("37a5b39e-8c6c-4f7f-871d-6b5d9e5b5f5a"),
                            Description = "Langages et frameworks",
                            Name = "Développement"
                        },
                        new
                        {
                            Id = new Guid("a2d8e4c1-4b1a-4d9a-9e1a-5f1e8a9d1c2b"),
                            Description = "Communication et leadership",
                            Name = "Soft Skills"
                        });
                });

            modelBuilder.Entity("SkillUp.Domaine.Entities.Evaluate", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Level")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.HasKey("UserId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("Evaluates");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("e1f2a3b4-c5d6-4e7f-8a9b-0c1d2e3f4a5b"),
                            SkillId = new Guid("b1c2d3e4-f5a6-4b7c-8d9e-0f1a2b3c4d5e"),
                            Comment = "",
                            LastUpdate = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = 5
                        },
                        new
                        {
                            UserId = new Guid("f1a2b3c4-d5e6-4f7a-8b9c-0d1e2f3a4b5c"),
                            SkillId = new Guid("b1c2d3e4-f5a6-4b7c-8d9e-0f1a2b3c4d5e"),
                            Comment = "",
                            LastUpdate = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = 1
                        });
                });

            modelBuilder.Entity("SkillUp.Domaine.Entities.Mentoring", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CollaboratorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MentorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CollaboratorId");

                    b.HasIndex("MentorId");

                    b.HasIndex("SkillId");

                    b.ToTable("Mentorings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1a2b3c4d-5e6f-4a7b-8c9d-0e1f2a3b4c5d"),
                            CollaboratorId = new Guid("f1a2b3c4-d5e6-4f7a-8b9c-0d1e2f3a4b5c"),
                            CreatedAt = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MentorId = new Guid("e1f2a3b4-c5d6-4e7f-8a9b-0c1d2e3f4a5b"),
                            SkillId = new Guid("b1c2d3e4-f5a6-4b7c-8d9e-0f1a2b3c4d5e"),
                            Status = 0
                        });
                });

            modelBuilder.Entity("SkillUp.Domaine.Entities.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Skills", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1c2d3e4-f5a6-4b7c-8d9e-0f1a2b3c4d5e"),
                            CategoryId = new Guid("37a5b39e-8c6c-4f7f-871d-6b5d9e5b5f5a"),
                            Name = "C# / EF Core"
                        },
                        new
                        {
                            Id = new Guid("c1d2e3f4-a5b6-4c7d-8e9f-0a1b2c3d4e5f"),
                            CategoryId = new Guid("37a5b39e-8c6c-4f7f-871d-6b5d9e5b5f5a"),
                            Name = "SQL Server"
                        });
                });

            modelBuilder.Entity("SkillUp.Domaine.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPasswordChanged")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e1f2a3b4-c5d6-4e7f-8a9b-0c1d2e3f4a5b"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jean@skillup.com",
                            FirstName = "Jean",
                            HashedPassword = "Y92gmIIn9/HsivTyLtWMY509RVjeMI1jCH8VdBkt8QVPWOfgbH0bMcJANnCXB0GK",
                            IsActive = true,
                            IsPasswordChanged = false,
                            LastName = "Mentor",
                            Role = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f1a2b3c4-d5e6-4f7a-8b9c-0d1e2f3a4b5c"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "alice@skillup.com",
                            FirstName = "Alice",
                            HashedPassword = "/W9gBsPa8we2uFArQsCyjvmeIE3LiiryE9biTMx7/JWg/cOYl6yajUsnrjWzAc9U",
                            IsActive = true,
                            IsPasswordChanged = false,
                            LastName = "Collab",
                            Role = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@skillup.com",
                            FirstName = "Admin",
                            HashedPassword = "YqpWnU8TuQ9Mkma000ZRdiIjwehAbBwf5+qt+TvaiLoGV9c4ktppxkVG82dNKs/q",
                            IsActive = true,
                            IsPasswordChanged = false,
                            LastName = "SkillUp",
                            Role = 2,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("SkillUp.Domaine.Entities.Evaluate", b =>
                {
                    b.HasOne("SkillUp.Domaine.Entities.Skill", "Skill")
                        .WithMany("Evaluations")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillUp.Domaine.Entities.User", "User")
                        .WithMany("Evaluations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkillUp.Domaine.Entities.Mentoring", b =>
                {
                    b.HasOne("SkillUp.Domaine.Entities.User", "Collaborator")
                        .WithMany("MentoringsAsCollaborator")
                        .HasForeignKey("CollaboratorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillUp.Domaine.Entities.User", "Mentor")
                        .WithMany("MentoringsAsMentor")
                        .HasForeignKey("MentorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkillUp.Domaine.Entities.Skill", "Skill")
                        .WithMany("Mentorings")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collaborator");

                    b.Navigation("Mentor");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("SkillUp.Domaine.Entities.Skill", b =>
                {
                    b.HasOne("SkillUp.Domaine.Entities.Category", "Category")
                        .WithMany("Skills")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SkillUp.Domaine.Entities.Category", b =>
                {
                    b.Navigation("Skills");
                });

            modelBuilder.Entity("SkillUp.Domaine.Entities.Skill", b =>
                {
                    b.Navigation("Evaluations");

                    b.Navigation("Mentorings");
                });

            modelBuilder.Entity("SkillUp.Domaine.Entities.User", b =>
                {
                    b.Navigation("Evaluations");

                    b.Navigation("MentoringsAsCollaborator");

                    b.Navigation("MentoringsAsMentor");
                });
#pragma warning restore 612, 618
        }
    }
}
